steps:
  - label: "Nvidia GPUs -- CUDA.jl"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.9
    agents:
      queue: "juliagpu"
      cuda: "*"
    command: |
      cd test/gpu
      julia --color=yes --project -e '
        using Pkg
        Pkg.develop(path="../..")
        Pkg.add("CUDA")
        Pkg.add("Krylov")
        Pkg.instantiate()
        include("nvidia.jl")'
    timeout_in_minutes: 30

  - label: "AMD GPUs -- AMDGPU.jl"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.9
    agents:
      queue: "juliagpu"
      rocm: "*"
      rocmgpu: "gfx1031"
    env:
      JULIA_NUM_THREADS: 4
      JULIA_AMDGPU_CORE_MUST_LOAD: "1"
      JULIA_AMDGPU_HIP_MUST_LOAD: "1"
      JULIA_AMDGPU_DISABLE_ARTIFACTS: "1"
    command: |
      cd test/gpu
      julia --color=yes --project -e '
        using Pkg
        Pkg.develop(path="../..")
        Pkg.add("AMDGPU")
        Pkg.add("Krylov")
        Pkg.instantiate()
        include("amd.jl")'
    timeout_in_minutes: 30

  - label: "Intel GPUs -- oneAPI.jl"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.9
    agents:
      queue: "juliagpu"
      intel: "*"
    command: |
      cd test/gpu
      julia --color=yes --project -e '
        using Pkg
        Pkg.develop(path="../..")
        Pkg.add("oneAPI")
        Pkg.add("Krylov")
        Pkg.instantiate()
        include("intel.jl")'
    timeout_in_minutes: 30
